
const String section1 = 'Section 1';
const String section2 = 'Section 2';
const String btnText = 'TEST BUTTON';
const String title = 'Title';
const String subTitle = 'Lorem ipsum dolor sit amet, consectetur adipisc'
    'ing elit. Duis convallis justo non nisi placerat maximus.';

const String body = 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. '
    'Vestibulum sed arcu non odio. Dapibus ultrices in iaculis nunc sed augue lacus viverra. Enim sed faucibus turpis in eu mi bibendum. Fringilla'
    ' ut morbi tincidunt augue interdum velit euismod in pellentesque. Egestas diam in arcu cursus euismod. Adipiscing at in tellus integer. Vel ri'
    'sus commodo viverra maecenas accumsan lacus vel. Sit amet nisl suscipit adipiscing bibendum est ultricies integer quis. Sed cras ornare arcu du'
    'i. Feugiat pretium nibh ipsum consequat. Nulla at volutpat diam ut venenatis tellus in metus. Mauris commodo quis imperdiet massa tincidunt nun'
    'c pulvinar sapien. Vel risus commodo viverra maecenas accumsan lacus vel facilisis. Non odio euismod lacinia at quis. Congue eu consequat ac fel'
    'is donec et odio pellentesque. Diam quam nulla porttitor massa id neque. Diam vulputate ut pharetra sit.'
    'Gravida neque convallis a cras semper auctor neque vitae. Suscipit tellus mauris a diam maecenas. At erat pellentesque adipiscing commodo elit at '
    'imperdiet dui. In massa tempor nec feugiat nisl pretium fusce id velit. Consectetur adipiscing elit ut aliquam purus sit amet luctus venenatis.'
    ' Mi ipsum faucibus vitae aliquet nec ullamcorper. Duis tristique sollicitudin nibh sit amet commodo nulla facilisi nullam. Urna et pharetra phar'
    'etra massa massa ultricies mi quis. Etiam dignissim diam quis enim lobortis scelerisque fermentum. Quisque id diam vel quam elementum pulvinar '
    'etiam non.'
    'Pellentesque massa placerat duis ultricies lacus sed turpis tincidunt id. Dictum at tempor commodo ullamcorper a lacus vestibulum sed arcu. Dui acc'
    'umsan sit amet nulla facilisi morbi tempus iaculis urna. Ut morbi tincidunt augue interdum velit euismod in. Morbi enim nunc faucibus a pellente'
    'sque sit amet. Sit amet nisl suscipit adipiscing bibendum est. Amet consectetur adipiscing elit pellentesque habitant. Leo urna molestie at ele'
    'mentum. Id cursus metus aliquam eleifend mi. Vitae purus faucibus ornare suspendisse sed nisi lacus sed. Eget egestas purus viverra accumsan.'
    ' Netus et malesuada fames ac turpis egestas sed tempus. Libero id faucibus nisl tincidunt. Eget sit amet tellus cras. Suscipit adipiscing bib'
    'endum est ultricies integer quis auctor elit sed. Aliquam etiam erat velit scelerisque in dictum. Duis at tellus at urna condimentum mattis pel'
    'lentesque. Scelerisque mauris pellentesque pulvinar pellentesque habitant morbi. A scelerisque purus semper eget duis at tellus.'
    'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. '
    'Vestibulum sed arcu non odio. Dapibus ultrices in iaculis nunc sed augue lacus viverra. Enim sed faucibus turpis in eu mi bibendum. Fringilla'
    ' ut morbi tincidunt augue interdum velit euismod in pellentesque. Egestas diam in arcu cursus euismod. Adipiscing at in tellus integer. Vel ri'
    'sus commodo viverra maecenas accumsan lacus vel. Sit amet nisl suscipit adipiscing bibendum est ultricies integer quis. Sed cras ornare arcu du'
    'i. Feugiat pretium nibh ipsum consequat. Nulla at volutpat diam ut venenatis tellus in metus. Mauris commodo quis imperdiet massa tincidunt nun'
    'c pulvinar sapien. Vel risus commodo viverra maecenas accumsan lacus vel facilisis. Non odio euismod lacinia at quis. Congue eu consequat ac fel'
    'is donec et odio pellentesque. Diam quam nulla porttitor massa id neque. Diam vulputate ut pharetra sit.'
    'Gravida neque convallis a cras semper auctor neque vitae. Suscipit tellus mauris a diam maecenas. At erat pellentesque adipiscing commodo elit at '
    'imperdiet dui. In massa tempor nec feugiat nisl pretium fusce id velit. Consectetur adipiscing elit ut aliquam purus sit amet luctus venenatis.'
    ' Mi ipsum faucibus vitae aliquet nec ullamcorper. Duis tristique sollicitudin nibh sit amet commodo nulla facilisi nullam. Urna et pharetra phar'
    'etra massa massa ultricies mi quis. Etiam dignissim diam quis enim lobortis scelerisque fermentum. Quisque id diam vel quam elementum pulvinar '
    'etiam non.'
    'Pellentesque massa placerat duis ultricies lacus sed turpis tincidunt id. Dictum at tempor commodo ullamcorper a lacus vestibulum sed arcu. Dui acc'
    'umsan sit amet nulla facilisi morbi tempus iaculis urna. Ut morbi tincidunt augue interdum velit euismod in. Morbi enim nunc faucibus a pellente'
    'sque sit amet. Sit amet nisl suscipit adipiscing bibendum est. Amet consectetur adipiscing elit pellentesque habitant. Leo urna molestie at ele'
    'mentum. Id cursus metus aliquam eleifend mi. Vitae purus faucibus ornare suspendisse sed nisi lacus sed. Eget egestas purus viverra accumsan.'
    ' Netus et malesuada fames ac turpis egestas sed tempus. Libero id faucibus nisl tincidunt. Eget sit amet tellus cras. Suscipit adipiscing bib'
    'endum est ultricies integer quis auctor elit sed. Aliquam etiam erat velit scelerisque in dictum. Duis at tellus at urna condimentum mattis pel'
    'lentesque. Scelerisque mauris pellentesque pulvinar pellentesque habitant morbi. A scelerisque purus semper eget duis at tellus.';
